### ISSUE TITLE
Set App Audio Device doesn't shows any device :(

### ISSUE THREAD

**Issue by AndrewLouisA4E** [GeekyEggo/SoundDeck#46] opened 2021-09-08 06:24 UTC
The only function that Sound Deck isn't working here, is the Set App Audio Device, I can change the title, process but Audio Device does not have any of my audio devices, shows nothing :c

**Comment by GeekyEggo** [comment] 2021-09-08 09:16
Hmm, this is odd, are you able to see the audio devices in the settings for a “Play Audio” action?

**Comment by AndrewLouisA4E** [comment] 2021-09-08 17:07
Yeap, Play Audio works fine, I send a screenshot below of my problem

The problem below
![image](https://user-images.githubusercontent.com/90305728/132553567-59e31ff7-d485-4bb2-9cbb-0ee5859c7e77.png)

Play Audio working fine
![image](https://user-images.githubusercontent.com/90305728/132553682-8999d724-aa94-4500-93ac-ec30ef458591.png)

**Comment by GeekyEggo** [comment] 2021-09-08 18:04
This is strange, as under the hood they use the same code, with the exception of a minor difference. Out of curiosity, what is your default communication device? And is it a virtual or physical device.
As part of #32 I’ve added some extra logging capabilities. I’m going to update areas that this ticket impacts to allow for better insight into what’s going on.

**Comment by AndrewLouisA4E** [comment] 2021-09-08 18:29
My default communication device
![image](https://user-images.githubusercontent.com/90305728/132564622-d65e9868-b750-4ad2-8050-df74748c8e17.png)

I guess they're virtual cable cause GO XLR created these audio lines but the GO XLR is physical.

**Comment by GeekyEggo** [comment] 2021-09-08 18:40
The GoXLR are physical, but that should work fine as I’m running a GoXLR too. Once I’ve got some extra logging in, would you be okay to run a beta version of the plug-in? I’ll post a link here when available.

**Comment by GeekyEggo** [comment] 2021-09-09 00:20
@AndrewLouisA4E, the latest beta, v2.1.3, includes more logging, hopefully sufficiently so to provide more insight in to what is happening. It would be great if you could;

1.  Download and install the latest beta version from here, [com.geekyeggo.sounddeck.streamDeckPlugin](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin)
1. Attempt to add a "Set App Audio Device" action.
1. Upload the log file located at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.sounddeck.sdPlugin\logs\sounddeck.log`.

**Comment by AndrewLouisA4E** [comment] 2021-09-09 02:05
Ok, check below :)
[sounddeck.log](https://github.com/GeekyEggo/SoundDeck/files/7132800/sounddeck.log)

**Comment by GeekyEggo** [comment] 2021-09-09 12:04
Thanks @AndrewLouisA4E, this looks to be an interoperability issue, i.e. one with Windows. I have created a fallback for the problem in the hopes of resolving it. Beta [v2.1.4](https://github.com/GeekyEggo/SoundDeck/raw/46-AppAudioInterop/dist/com.geekyeggo.sounddeck.streamDeckPlugin) can now be downloaded. Once installed, could you please follows steps 2 and 3 again.

**Comment by AndrewLouisA4E** [comment] 2021-09-10 10:42
WORKED! :D Thanks!
![image](https://user-images.githubusercontent.com/90305728/132841555-d937a1c1-c614-4b48-a4a7-4e8a2e532be7.png)

[sounddeck.log](https://github.com/GeekyEggo/SoundDeck/files/7143242/sounddeck.log)

**Comment by GeekyEggo** [comment] 2021-09-10 12:02
Fantastic news! Thanks for letting me know, @AndrewLouisA4E.

**Comment by GeekyEggo** [comment] 2021-09-10 13:11
Closed by bc8054fdfcb08460baf4edb5926ae74268048582.

**Closed by GeekyEggo** 2021-09-10 13:11 UTC
Labels: bug 🐞

**Comment by GeekyEggo** [comment] 2021-09-12 11:29
@AndrewLouisA4E, question, are you running Windows 11? This change has resolved the issue for someone else, and I’m trying to identify if changes in Windows 11 are the root cause.

**Comment by AndrewLouisA4E** [comment] 2021-09-12 15:10
Hi @GeekyEggo, yes I'm using Windows 11
